// export interface MoneyAllocation {
//   Id: number,
//   StockID: number,
//   CustomerID: number,
//   ReserveDays: number,
//   PaidPercent: number,
//   BalancePercent: number,
//   AssignedRatio: number,
//   AllocatedAmount: number,
//   BalanceAmount: number,
//   TotalCNF: number,
//   AfterDue: number,

//   ReleaseOk: boolean,
//   Release: boolean,
//   SureCheck: boolean,
//   ShipHold: boolean,
//   isActive: boolean,

//   CourierAddress: string,
//   ShipName: string,
//   VoyageNumber: string,
//   ReleaseDate: Date,
//   ETD: Date,
//   ETA: Date,
//   CreatedOn: Date,
//   ConsigneeID: number,
//   CourierID: number,
//   BuyingCost: number,
//   DomesticCharge: number,
//   ExtraTransport: number,
//   Inspection: number,
//   Repairs: number,
//   Insurance: number,
//   PortStorage: number,
//   PhotoCharges: number,
//   ExtraJobs: number,
//   Vanning: number,
//   Freight: number,
//   CourierCharge: number,
//   TotalCost: number,
//   Profit: number,
//   CreatedBy: number

// }
export interface MoneyAllocation {
  id: number,
  stockID: number,
  customerID: number,
  reserveDays: number,
  paidPercent: number,
  balancePercent: number,
  assignedRatio: number,
  allocatedAmount: number,
  balanceAmount: number,
  totalCNF: number,
  afterDue: number,

  releaseOk: boolean,
  release: boolean,
  sureCheck: boolean,
  shipHold: boolean,
  isActive: boolean,

  courierAddress: string,
  shipName: string,
  voyageNumber: string,
  releaseDate: Date,
  etd: Date,
  eta: Date,
  createdOn: Date,
  consigneeID: number,
  courierID: number,
  buyingCost: number,
  domesticCharge: number,
  extraTransport: number,
  inspection: number,
  repairs: number,
  insurance: number,
  portStorage: number,
  photoCharges: number,
  extraJobs: number,
  vanning: number,
  freight: number,
  courierCharge: number,
  totalCost: number,
  profit: number,
  createdBy: number
}
