// export interface SalesOrder {
//   Id: number ,
//   SalePrice: number,
//   StockId: number
//   ConsigneeId: number ,
//   CourierId: number ,
//   MoneyAllocationID: number ,
//   SONumber: string ,
//   InsuranceCost: string ,
//   FreightCost: string ,
//   FOB: string ,
//   SoldPrice: string ,
//   Remarks: string ,
//   DestCountry: string ,
//   FreightOptions: string ,
//   CountryName: string ,
//   PortName: string ,
//   BLType: string ,
//   ShipmentTermType: string ,
//   IncoTerm: string ,
//   PaymentMode: string ,
//   DepositRatio: string ,
//   BankName: string ,
//   CreatedByUser: string ,
//   CustomerCode: string ,
//   Name: string ,
//   StockCode: string ,
//   CarName: string ,
//   ChasisNumber: string ,
//   SODate: Date,
//   isActive: boolean




// }
export interface SalesOrder {
  id: number,
  salePrice: number,
  stockId: number,
  consigneeId: number,
  courierId: number,
  moneyAllocationID: number,
  soNumber: string,
  insuranceCost: string,
  freightCost: string,
  fob: string,
  soldPrice: string,
  remarks: string,
  destCountry: string,
  freightOptions: string,
  countryName: string,
  portName: string,
  blType: string,
  shipmentTermType: string,
  incoTerm: string,
  paymentMode: string,
  depositRatio: string,
  bankName: string,
  createdByUser: string,
  customerCode: string,
  name: string,
  stockCode: string,
  carName: string,
  chasisNumber: string,
  soDate: Date,
  isActive: boolean
}
